services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clothes_store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - service_network

  tomcat:
    image: tomcat:9.0
    container_name: tomcat_server
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps
    networks:
      - service_network

volumes:
  mysql_data:

networks:
  service_network:
    driver: bridge